### ISSUE TITLE
Should removing a pipe remove a view?

### ISSUE THREAD

**Issue by arl** [josharian/pex#1]
For a _toy_, that's an awesome one ! Thank you ❤️ 

So, adding pipes to the command naturally adds new views to the screen.

While hacking a command, I found a way to simplify it and ended up needing to remove a pipe, I was then expecting the number of view to decrease, so as to match the number of pipes in the command.

Do you think that would be a useful addition to pex?

**Comment by josharian** [comment]
Oh yeah, that's a straight up bug. Oops!
